### ISSUE TITLE
Show last order on profile page in admin

### ISSUE THREAD

**Issue by mgvd** [VOKO-Utrecht/voko#301]
Members come and go. Sometimes it's hard to see when members are still active and ordering at Voko.
If the administrator can see when people placed their latest order, they can assess better if that member is still active or is a sleeping member of Voko

**Comment by bveldkamp** [comment]
Where exactly should this go? I had a look at this: 

Adding the last order date to the users overview page (i.e. /admin/acounts/vokouser) requires just a few lines of code, because we are already overriding the default Django admin page here, and adding a single field is straightforward. 

Adding it to the _userprofiles_ page (/admin/accounts/userprofile) otoh looks to be a bit more complicated, because it is still uses the default Django admin page. As far as I can see, we would need to override the entire page to be able to add a single field, similar to how the user overview page now works.

Or should this field be added to a user's page, rather than the overview page? ( /admin/accounts/vokouser/1/change or /admin/accounts/userprofile/1/change , both are also still the default Django pages)

**Comment by mgvd** [comment]
In that case I would suggest adding it to the admin user overview page (
 /admin/acounts/vokouser ), only. The goal is that the admin team can see
whether a user is active or not by placing orders.




Op ma 11 sep 2023 om 10:55 schreef Berend Veldkamp ***@***.***
